[package]
org = "ballerinax"
name = "mysql"
version = "1.13.2"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "MySQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241025-103700-5c9e6a27"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mysql-native"
version = "1.13.2"
path = "../native/build/libs/mysql-native-1.13.2-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.14.2"
path = "./lib/sql-native-1.14.2-20241028-114300-2672942.jar"
